server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    email: /email/**
#    participants: /paticipants/**
#zuul:
#  routes:
#    races: /races/**
#    participants: /paticipants/**